version: "3.8"
services:

  dev-api: 
    build:
      context: .
      target: dev
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
  test-api:
    build:
      context: .
      target: test
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    ports:
      - "3001:3000"
  prod-api:
    build: .
    restart: unless-stopped
    ports:
      - "3002:3000"
  db:
    image: mysql:8
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
